### ISSUE TITLE
TypeError: global[Symbol.for(...)] is not a function

### ISSUE THREAD

**Issue by duartealexf** [adonisjs/assembler#16]
## Package version

3.0.6

## Node.js and npm version

- Node v14.5.0
- NPM 6.14.5

## Sample Code (to reproduce the issue)

https://github.com/duartealexf/adonisjs5-test

## BONUS (a sample repo to reproduce the issue)

Just run `npm run test` from the repository. The console should show the error:

```
TypeError: global[Symbol.for(...)] is not a function
```

All I did was follow instructions from:

- https://preview.adonisjs.com/guides/quick-start
- https://preview.adonisjs.com/guides/database/setup
- https://preview.adonisjs.com/blog/running-tests-in-adonisjs-v5

**Comment by RomainLanz** [comment]
Hey @duartealexf! 👋 

You are missing the property `cardId` on your `List` model.
I'd recommend to start the Http server following [this article](https://preview.adonisjs.com/blog/running-tests-in-adonisjs-v5#setup-for-adonisjs) to have proper error.

**Comment by duartealexf** [comment]
Hi @RomainLanz

Thanks! I added the `cardId` but the issue remained. It only fixed after I started the HTTP server like the article mentioned. Thank you.
