### ISSUE TITLE
ace serve --watch results error on Raspberry Pi

### ISSUE THREAD

**Issue by janez89** [adonisjs/assembler#17]
When I start node ace serve --watch on Raspberry Pi then I get an error.

I've already explained the situation on this discussion: https://github.com/adonisjs/core/discussions/1914

## Package version
├── @adonisjs/assembler@3.0.6
├── @adonisjs/auth@5.0.2
├── @adonisjs/core@5.0.4-preview-rc-2
├── @adonisjs/lucid@9.0.3
├── @adonisjs/mail@5.1.0
├── @adonisjs/redis@5.0.8
├── @adonisjs/repl@1.1.5
├── @adonisjs/session@4.0.5
├── @adonisjs/view@3.0.8
├── adonis-preset-ts@1.1.0
├── eslint@7.14.0
├── eslint-config-prettier@6.15.0
├── eslint-plugin-adonis@1.0.15
├── eslint-plugin-prettier@3.1.4
├── luxon@1.25.0
├── node-fetch@2.6.1
├── pino-pretty@4.3.0
├── prettier@2.2.0
├── proxy-addr@2.0.6
├── reflect-metadata@0.1.13
├── sqlite3@5.0.0
├── typescript@4.1.2
├── youch@2.1.1
└── youch-terminal@1.0.1

## Node.js and npm version
NodeJS: v14.15.0
NPM: 6.14.8

## Sample Code (to reproduce the issue)
https://github.com/adonisjs/core/discussions/1914

**Comment by thetutlage** [comment]
I don't have a `Raspberry Pi `, so there is no way for me to reproduce the issue. If someone can do that and provide a fix, I am happy to accept the PR

**Comment by janez89** [comment]
Thanks to the response. I had no time. Next week I will create a PR for this.

**Comment by janez89** [comment]
I was blind. You already resolved. :)
