### ISSUE TITLE
AdonisJS cannot be configured with Turborepo

### ISSUE THREAD

**Issue by Predeactor** [adonisjs/assembler#42]
I am sending this issue here as this is where the `node ace configure tests` is invocated, and where the problem is located.

When creating a new Adonis application, Adonis will try to set up tests (no matter which project structure you have chosen), but tests are dependents of the adonis-preset-ts module, and Adonis will try to retrieve the `tsconfig` of this module by searching in the node_modules he has created in his folder. However, the problem with Turborepo is that it will usually install dependencies/modules in the root folder of the repo, like this:
```
my_turborepot/
├─ apps/
│  ├─ adonis_app/
│  │  ├─ node_modules/   <-- Where Adonis think dependencies goes
│  │  ├─ package.json
│  ├─ my_other_app/
│  │  ├─ node_modules/
│  │  ├─ package.json
├─ node_modules/         <-- Where dependencies goes
├─ README.md
```

As such, if you try to set up an Adonis application using `create-adonis-ts-app`, the following error is raised:
![image](https://user-images.githubusercontent.com/61093863/164905236-0b6063dc-51c2-47df-9ce2-3f61be379c56.png)

I have no real idea on how to support those, and this is why I'm just dropping an issue rather than a PR.

## Package version
`version: 5.6.2`

## Node.js and npm version
`Node: v16.14.0
npm: v8.5.2
Yarn: 1.22.18`

## Sample Code (to reproduce the issue)
*Not relevant*

## BONUS (a sample repo to reproduce the issue)
*Not relevant*

**Comment by thetutlage** [comment]
Assembler does not find the `adonis-preset-ts/tsconfig` file. It is basically a file that your application `tsconfig.json` is extending. If you open `tsconfig.json` file of your app, following is the first line.

```json
{
  "extends": "./node_modules/adonis-preset-ts/tsconfig",
}
```

So basically this needs to be fixed to work with turborepo. I do not use turborepo, so I will need your help to find a solution

**Comment by Predeactor** [comment]
Sure, I'll do my best to help you as much as I can!
You can start by seeing what Turborepo is to have a quick look: https://turborepo.org/

In my end, I'll start thinking of a solution, and I'll come back to you when I might have something fresh. I'll be listening to your comments until then!

**Comment by Predeactor** [comment]
As you might have noticed already, I've sent a PR to fix the little bug here. Since it is effectively not related to Assembler, I apologize for sending my issue here and not making deeper research before sending this issue. I'll leave you the decision to close it or not, since I've opened a pull request.
Otherwise, thank you for your time with me!
