### ISSUE TITLE
Add `make:test-suite` command

### ISSUE THREAD

**Issue by brkn** [adonisjs/assembler#43]
## Why this feature is required (specific use-cases will be appreciated)?

Swiftly bootstrapping other test suites. Right now assembler only creates a functional suite. Adding new suites requires manually editing file(s?).

## Have you tried any other work arounds?

Other workaround could be doing this manually.

## Are you willing to work on it with little guidance?

Sure!

**Comment by thetutlage** [comment]
Was added in https://github.com/adonisjs/assembler/pull/48. I think we forgot to link the issue
