### ISSUE TITLE
The glob-parent vulnerability issue

### ISSUE THREAD

**Issue by dinoluck** [adonisjs/assembler#44]
## Package version
5.6.2

## Node.js and npm version
v16.13.2 and 8.1.2

## Sample Code (to reproduce the issue)
Core issue on npm install

## BONUS (a sample repo to reproduce the issue)
Running any npm i will raise 5 high severity issues, output of npm audit:

# npm audit report

glob-parent  <5.1.2
Severity: high
Regular expression denial of service in glob-parent - https://github.com/advisories/GHSA-ww39-953v-wcq6
No fix available
node_modules/cpy/node_modules/glob-parent
  fast-glob  <=2.2.7
  Depends on vulnerable versions of glob-parent
  node_modules/cpy/node_modules/fast-glob
    globby  8.0.0 - 9.2.0
    Depends on vulnerable versions of fast-glob
    node_modules/cpy/node_modules/globby
      cpy  7.0.0 - 8.1.2
      Depends on vulnerable versions of globby
      node_modules/cpy
        @adonisjs/assembler  *
        Depends on vulnerable versions of cpy
        node_modules/@adonisjs/assembler

5 high severity vulnerabilities

Is there a way of mitigating/fix this?

**Comment by RomainLanz** [comment]
Hey @dinoluck! 👋🏻 

Please read https://github.com/adonisjs/core/issues/3333#issuecomment-968345404
