### ISSUE TITLE
Add flag for copying .env file after build

### ISSUE THREAD

**Issue by Julien-R44** [adonisjs/assembler#57]
Something I always keep forgetting to do. After my build, I constantly come and copy my `.env` file into the generated build folder. 

Is it ok if I add a `copyEnv` flag on the build command? Any better suggestions?

**Comment by RomainLanz** [comment]
You don't necessarily want to copy the `.env` file in production, especially since the one you copy has devs' values.

**Comment by Julien-R44** [comment]
Yep but the flag would be optional. Here is my workflow when I deploy some applications: 

- I clone the repo on the VPS
- I change the .env file to have prod values.
- Then I build and launch with PM2

So most of the time I have some CI that takes care of copying the .env etc. But sometimes, on test applications, I don't make a CI. So once in a while, I connect to the VPS with SSH, and I do the build manually. And I forget the .env every time :p

**Comment by Julien-R44** [comment]
In retrospect, I don't think it's worth adding. Adding a "cp .env build/.env" in the npm build command is enough. Maybe to reconsider later, but closing it for now
