### ISSUE TITLE
still reload server when typescript file that match metaFiles in rc that has `reloadServer` to false

### ISSUE THREAD

**Issue by SH8GH** [adonisjs/assembler#68]
### Package version

@adonisjs/assembler@7.1.1

### Describe the bug

[here](https://github.com/adonisjs/assembler/blob/f6bb870aa5eec3301b29e24865ddbd634f6aa64c/src/dev_server.ts#L240C1-L247C4)

i don't know which it a bug or feature request but when `--watch` even i ignore `resources/**` typescript file inside there still reload.

should we change to this?

```ts
  /**
   * Handles TypeScript source file change
   */
  #handleSourceFileChange(action, port, relativePath) {
    const isMatch = this.#options.metaFiles.find((item) => {
      if (!item.reloadServer) {
        return picomatch(item.pattern)(relativePath)
      }
      return false
    })

    this.#clearScreen();
    this.#logger.log(`${this.#colors.green(action)} ${relativePath}`);
    if (typeof isMatch === 'undefined') {
      this.#restartHTTPServer(port);
    }
  }
```

that maybe we can ignore http server restart save time on development
and reproduce:

- create adonisjs v6 using `web-starter-kit`
- in adonisrc add meta 
```ts
  metaFiles: [
    // {
    //   pattern: 'resources/views/**/*.edge',
    //   reloadServer: false,
    // },
    {
      pattern: 'public/**',
      reloadServer: false,
    },
    {
      pattern: 'resources/**',
      reloadServer: false,
    },
  ],
```
- create typescript file in `/resources` folder
- start web server using `--watch`
- save typescript file in `/resources` folder

you will see the server reload then `/resources` folder you completed ignore, it not getting full potential of `@adonisjs/vite` hot-reload

### Reproduction repo

https://github.com/SH8GH/ssembler.file

**Comment by SH8GH** [comment]
sorry for first time i open issues

**Comment by thetutlage** [comment]
Meta files are for files other than the TypeScript files, or the files included by the `tsconfig.json` file. If you want this file to be ignored, then ignore it inside `tsconfig.json` and all should be good.

If you are using TypeScript files for the frontend codebase, then you should create a dedicated `tsconfig.json` file inside the `resources` directory. Check docs for same. https://docs.adonisjs.com/guides/assets-bundling#configuring-typescript

Also, ignore frontend codebase from the `tsconfig.json` file inside the root of your project.

**Comment by thetutlage** [comment]
Closing since no response from the issue reporter and not actionable as well
