### ISSUE TITLE
doesn't recognize build command

### ISSUE THREAD

**Issue by venki0004** [adonisjs/assembler#69]
### Package version

7.1.1

### Describe the bug

**# Missing "build" command in `node ace`**

**## Description**

**When running `node ace build --production`, I'm encountering the following error:**

```
[ error ]  "build" command not found
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! adonis@1.1.0 build: `node ace build --production`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the adonis@1.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```
**## Steps to Reproduce**
1.  Update assembler to  "@adonisjs/assembler": "^7.1.1",
1.  Run `node ace build --production` in the project directory.
2.  Observe the error message.

**## Environment**

-   Node.js version: V14.15.5
-   npm version: V6.14.11
-   Adonis version: V5
-   Operating system: macOS
<img width="838" alt="image" src="https://github.com/adonisjs/assembler/assets/74340982/7b04369a-c9c2-4cb2-bd83-e51a160d9f5d">

**Comment by RomainLanz** [comment]
Hey @venki0004! 👋🏻 

Version `7` of the assembler package is for AdonisJS 6; please roll back your version to `^5.9.6`.

**Comment by venki0004** [comment]
Thank you for letting me know about the version compatibility issue with the assembler package. 
I'll roll back the version to ^5.9.6 as requested for compatibility with AdonisJS 6.
