### ISSUE TITLE
Error running npm run build in Adonis 6

### ISSUE THREAD

**Issue by igortrinidad** [adonisjs/assembler#70]
### Package version

 @adonisjs/assembler@7.1.1

### Describe the bug

Hello there,

I'm not able to build the application using `npm run build` command:

node version: 21.6.1

![image](https://github.com/adonisjs/assembler/assets/13478652/939fd323-9936-4f54-a500-e3e8f9704731)

├── @adonisjs/assembler@7.1.1
├── @adonisjs/auth@9.1.1
├── @adonisjs/core@6.2.2
├── @adonisjs/cors@2.2.1
├── @adonisjs/eslint-config@1.2.1
├── @adonisjs/lucid@20.1.0
├── @adonisjs/prettier-config@1.2.1
├── @adonisjs/redis@8.0.1
├── @adonisjs/session@7.1.1
├── @adonisjs/tsconfig@1.2.1

### Reproduction repo

npm run build

**Comment by igortrinidad** [comment]
The error happens on Digital Ocean apps too:

```
2024-02-13T18:42:23.731825034Z [34m│[0m [ error ] ENOENT: no such file or directory, open '/home/node/app/build/ace.js'
2024-02-13T18:42:23.731847676Z [34m│[0m           at async open (node:internal/fs/promises:633:25)
2024-02-13T18:42:23.731850337Z [34m│[0m           at async Object.writeFile (node:internal/fs/promises:1212:14)
2024-02-13T18:42:23.731853175Z [34m│[0m           at async #createAceFile (file:///home/node/app/node_modules/@adonisjs/assembler/build/index.js:269:5)
2024-02-13T18:42:23.731855314Z [34m│[0m           at async Bundler.bundle (file:///home/node/app/node_modules/@adonisjs/assembler/build/index.js:295:5)
2024-02-13T18:42:23.731857502Z [34m│[0m           at async Build.run (file:///home/node/app/node_modules/@adonisjs/core/build/commands/build.js:93:35)
2024-02-13T18:42:23.731860048Z [34m│[0m           at async Build.exec (file:///home/node/app/node_modules/@adonisjs/core/build/modules/ace/commands.js:51:28)
2024-02-13T18:42:23.731862352Z [34m│[0m           at async #execMain (file:///home/node/app/node_modules/@adonisjs/ace/build/index.js:1481:7)
2024-02-13T18:42:23.731864497Z [34m│[0m           at async AceProcess.handle (file:///home/node/app/node_modules/@adonisjs/core/build/src/ignitor/ace.js:66:9)
2024-02-13T18:42:23.755979208Z [34m│[0m error building image: error building stage: failed to execute command: waiting for process to exit: exit status 1
2024-02-13T18:42:23.812638405Z [34m│[0m 
2024-02-13T18:42:23.812664914Z [34m│[0m command exited with code 1
2024-02-13T18:42:23.813017743Z [34m│[0m 
```

**Comment by RomainLanz** [comment]
Hey @igortrinidad! 👋🏻 

We cannot help you with the amount of information you shared.
As stated in the PR, please provide a repository with the minimum amount of code needed to reproduce your issue.

**Comment by igortrinidad** [comment]
Hi @RomainLanz , 

That's the repository:

[https://github.com/igortrinidad/adonis-build-error](https://github.com/igortrinidad/adonis-build-error)


To reproduce:

- `git clone https://github.com/igortrinidad/adonis-build-error.git`
- `cd adonis-build-error`
- `npm install`
- `node ace migration:refresh --seed`
- `npm run dev`  - working as expected, you can try out the /general/graphql/interface route
- `npm run build` - it should work there
- `npm run test:build` - it throws ts / import errors depending on how I'm trying to import, I tried with .ts, without extension, with js, using relative imports, using alias (preferred way)...

**Comment by RomainLanz** [comment]
I am not sure what's the error.

The code builds fine (except for some TypeScript errors):
![CleanShot 2024-02-14 at 11 08 19@2x](https://github.com/adonisjs/assembler/assets/2793951/57736c1a-b47b-4e94-99e6-4c41ad3d6ec8)

You also have some issues directly in your code regarding your imports.
For example, in your route file, you are using Node subpath imports by still adding the extension. This should be avoided since it will not work in production.

```diff
- import '#app/modules/general/routes.ts'
+ import '#app/modules/general/routes'
```

**Comment by igortrinidad** [comment]
Did you tried to run the builded application there? It throws different errors based on how we config the imports paths on tsconfig and package.json and how we actually import them in code...

![image](https://github.com/adonisjs/assembler/assets/13478652/88804cd1-c725-4fef-9f09-71a554efd396)

**Comment by RomainLanz** [comment]
Read my last sentence.

**Comment by igortrinidad** [comment]
Sorry @RomainLanz don't you think I already tried removing extension from imports, adding extension again, change the ts config in tsconfig AND in package.json (why?), tried relative imports everywhere, tried alias imports everywhere (preferred way)...

Look guys, I'm very grateful for the work you guys have done in Adonis, I love the framework and I use it in more than a dozen production applications, half of them V4, half V5, and I'm contributing where the project for about 3 years, it's a small contribution, but I'm just an individual trying to motivate the project... 

I've been working on this small mockup for about two weeks and it still has been working yet... This very small mockup it's what I usually need in any backend applications with any framework I used to use: Laravel, Adonis V4, Adonis V5, Express, Fastify, Flasky;

In order to test if a given framework attends the common application specs that I'm used to build and check the availability to adopt it, I should be able to, at least, use/create some features using the framework;

- multi authentication
- split their route into modules to separate the concerns
- integrate with third party libraries/feats like Graphql, Socket, AWS, Queue - which I already have my services classes working for any of these frameworks, so I just update the code style to match the "new pattern" or language - but the business rule remains the same between them...

But in this case, it seems that there are too many breaking changes and the Adonis V6 isn't ready to be used yet in a not-so-common environment / or not fully tested yet.

And it raises some questions regarding Adonis governance; 
- Why stop to maintain / updating / bug fix the working and approved version of the framework?
- create a new version with too much breaking change on every major change?
- update the main website to the new version prematurely?

All of these stimulating people to adopt the new version if it isn't ready / fully tested yet?

**Comment by RomainLanz** [comment]
I have no idea where you are going, and I don't like what you're implying.

After doing **exactly** what I said in my last message (fix your imports), your server ran fine in production mode.

![CleanShot 2024-02-14 at 12 47 53@2x](https://github.com/adonisjs/assembler/assets/2793951/bcad74a9-a721-46bf-8542-ecb2bc05bdb8)

The only caveats are in your GraphQL service because you wrote a broken code that dynamically imports a TypeScript file, which does not exist in production. Your path is also not correctly built.

```ts
const modulesFiles = fs
  .readdirSync(modulesPath)
  .filter((file) => !file.includes('.map'))
  .map((file) => file.replace('.ts', '.js')
```

I would recommend being a bit more respectful next time you are asking for help, especially since the issue is on your side.

**Comment by igortrinidad** [comment]
@RomainLanz I'm sorry if you feel I was disrespectful, that wasn't my intention at all. And thank you very much for all your help and availability to try to understand what is going on... 

Do you mind to share the repository which you made it work so I can try with your changes? And which node version did you test it?

I believe I tried the changes you mentioned and commit them out, but it will be helpful see a working example...

**Comment by RomainLanz** [comment]
Here you go: https://github.com/igortrinidad/adonis-build-error/pull/1/files
