### ISSUE TITLE
Remove the host rewrite on dev_server to allow running the application on Digital Ocean apps

### ISSUE THREAD

**Issue by igortrinidad** [adonisjs/assembler#72]
### Package version

7.1.1

### Describe the bug

I'm trying to deploy the application using Digital Ocean Apps.

Firstly I tried to deploy it using the build, but for other reasons, the build isn't fully working right now... So I'm trying to deploy using the dev server, the thing is that the dev_server is rewriting the host from 0.0.0.0 to 127.0.0.1 which breaks the deployment for the DO apps...

There's really a need to rewrite it?

https://github.com/adonisjs/assembler/blob/develop/src/dev_server.ts

**Comment by RomainLanz** [comment]
Hey @igortrinidad! 👋🏻 

The host is not rewritten; it is only changed on the message display in the CLI to make it a clickable link.

**Comment by igortrinidad** [comment]
I inspected the code and I saw that it shouldn't change the host, just the message, but did try to access the 0.0.0.0 server? Here it didn't work, but when I used the forked version it worked properly... Anyway, I needed this change to use dev mode in production because I'm not able to yet - my real problem is how to use Adonis V6 in production...
